//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuplicateFileTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DuplicateFileTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte size units of the number entered in Min/Max file size field..
        /// </summary>
        public static string Config_ByteSizeUnit_Description {
            get {
                return ResourceManager.GetString("Config_ByteSizeUnit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size units.
        /// </summary>
        public static string Config_ByteSizeUnit_Name {
            get {
                return ResourceManager.GetString("Config_ByteSizeUnit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file comparing algorithm does not compare the files byte to byte, but divides the file to chunks and calculates the hash of the chunks and then compares the hash, this parameter specifies the size of the chunk to be used. A smaller value will lead to a faster comparison but will consume more memory, a bigger value will lead to slower comparison, but will require less memory..
        /// </summary>
        public static string Config_ComparableFileHash_HashChunkSize_Description {
            get {
                return ResourceManager.GetString("Config_ComparableFileHash_HashChunkSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash chunk size.
        /// </summary>
        public static string Config_ComparableFileHash_HashChunkSize_Name {
            get {
                return ResourceManager.GetString("Config_ComparableFileHash_HashChunkSize_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison match points with value greater or equal to his value will cause for the files to be considered matching.
        /// </summary>
        public static string Config_Comparer_CompleteMatch_Description {
            get {
                return ResourceManager.GetString("Config_Comparer_CompleteMatch_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparer Match Value.
        /// </summary>
        public static string Config_Comparer_CompleteMatch_Name {
            get {
                return ResourceManager.GetString("Config_Comparer_CompleteMatch_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison match points with value less or equal to his value will cause for the files to be considered mismatching.
        /// </summary>
        public static string Config_Comparer_CompleteMismatch_Description {
            get {
                return ResourceManager.GetString("Config_Comparer_CompleteMismatch_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparer Mismatch Value.
        /// </summary>
        public static string Config_Comparer_CompleteMismatch_Name {
            get {
                return ResourceManager.GetString("Config_Comparer_CompleteMismatch_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the comparer.
        /// </summary>
        public static string Config_Comparer_Description_Description {
            get {
                return ResourceManager.GetString("Config_Comparer_Description_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparer Description.
        /// </summary>
        public static string Config_Comparer_Description_Name {
            get {
                return ResourceManager.GetString("Config_Comparer_Description_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the files match points generated by comparison is greater or equal than this value the search engine will consider those values matching.
        /// </summary>
        public static string Config_Comparer_MatchThreshold_Description {
            get {
                return ResourceManager.GetString("Config_Comparer_MatchThreshold_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparer Match Threshold.
        /// </summary>
        public static string Config_Comparer_MatchThreshold_Name {
            get {
                return ResourceManager.GetString("Config_Comparer_MatchThreshold_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name of the comparer.
        /// </summary>
        public static string Config_Comparer_Name_Description {
            get {
                return ResourceManager.GetString("Config_Comparer_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparer Name.
        /// </summary>
        public static string Config_Comparer_Name_Name {
            get {
                return ResourceManager.GetString("Config_Comparer_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled the program will skip the hidden files and directories..
        /// </summary>
        public static string Config_ExcludeHiddenFiles_Description {
            get {
                return ResourceManager.GetString("Config_ExcludeHiddenFiles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude hidden files and directories.
        /// </summary>
        public static string Config_ExcludeHiddenFiles_Name {
            get {
                return ResourceManager.GetString("Config_ExcludeHiddenFiles_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled the program will skip the OS files and directories, such as windows directory and others known directories that belong to the operating system..
        /// </summary>
        public static string Config_ExcludeOsFiles_Description {
            get {
                return ResourceManager.GetString("Config_ExcludeOsFiles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude OS files and directories.
        /// </summary>
        public static string Config_ExcludeOsFiles_Name {
            get {
                return ResourceManager.GetString("Config_ExcludeOsFiles_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled the program will skip the files and directories that has the system attribute set..
        /// </summary>
        public static string Config_ExcludeSystemFiles_Description {
            get {
                return ResourceManager.GetString("Config_ExcludeSystemFiles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude system files and directories.
        /// </summary>
        public static string Config_ExcludeSystemFiles_Name {
            get {
                return ResourceManager.GetString("Config_ExcludeSystemFiles_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if the listed extensions have to be included or excluded from the search.
        /// </summary>
        public static string Config_ExtensionInclusionType_Description {
            get {
                return ResourceManager.GetString("Config_ExtensionInclusionType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension inclusion type.
        /// </summary>
        public static string Config_ExtensionInclusionType_Name {
            get {
                return ResourceManager.GetString("Config_ExtensionInclusionType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file size above which the file will be excluded from the results.
        /// </summary>
        public static string Config_MaxFileSize_Description {
            get {
                return ResourceManager.GetString("Config_MaxFileSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum file size.
        /// </summary>
        public static string Config_MaxFileSize_Name {
            get {
                return ResourceManager.GetString("Config_MaxFileSize_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the maximum count of files that the program will keep open after reaching which the program will start closing the files opened previously. The low value will negatively impact performance, the high value will cause the program to consume to many resources..
        /// </summary>
        public static string Config_MaximumFilesOpenedAtOnce_Description {
            get {
                return ResourceManager.GetString("Config_MaximumFilesOpenedAtOnce_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum files opened at once.
        /// </summary>
        public static string Config_MaximumFilesOpenedAtOnce_Name {
            get {
                return ResourceManager.GetString("Config_MaximumFilesOpenedAtOnce_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file size below which the file will be excluded from the results.
        /// </summary>
        public static string Config_MinFileSize_Description {
            get {
                return ResourceManager.GetString("Config_MinFileSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum file size.
        /// </summary>
        public static string Config_MinFileSize_Name {
            get {
                return ResourceManager.GetString("Config_MinFileSize_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many duplicate groups to display on a single results page.
        /// </summary>
        public static string Config_Results_Items_Per_Page_Description {
            get {
                return ResourceManager.GetString("Config_Results_Items_Per_Page_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate groups per page.
        /// </summary>
        public static string Config_Results_Items_Per_Page_Name {
            get {
                return ResourceManager.GetString("Config_Results_Items_Per_Page_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if the results should be in a descending or ascending order.
        /// </summary>
        public static string Config_Results_Sort_Descending_Description {
            get {
                return ResourceManager.GetString("Config_Results_Sort_Descending_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results Sorting Direction.
        /// </summary>
        public static string Config_Results_Sort_Descending_Name {
            get {
                return ResourceManager.GetString("Config_Results_Sort_Descending_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified the duplicate group parameter to use for sorting results.
        /// </summary>
        public static string Config_Results_Sort_Order_Description {
            get {
                return ResourceManager.GetString("Config_Results_Sort_Order_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting Order.
        /// </summary>
        public static string Config_Results_Sort_Order_Name {
            get {
                return ResourceManager.GetString("Config_Results_Sort_Order_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file comparer that should be used to compare files during the duplicates search..
        /// </summary>
        public static string Configur_SelectedFileComparerGuid_Description {
            get {
                return ResourceManager.GetString("Configur_SelectedFileComparerGuid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file comparer.
        /// </summary>
        public static string Configur_SelectedFileComparerGuid_Name {
            get {
                return ResourceManager.GetString("Configur_SelectedFileComparerGuid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the file &apos;{0}&apos;. .
        /// </summary>
        public static string Error_ComparableFileHash_Cant_read_the_file {
            get {
                return ResourceManager.GetString("Error_ComparableFileHash_Cant_read_the_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File comparer type mismatch.
        /// </summary>
        public static string Error_ComparableFileHash_CompareTo_File_Comparer_type_mismatch {
            get {
                return ResourceManager.GetString("Error_ComparableFileHash_CompareTo_File_Comparer_type_mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing with the file hash object that has a different fragment size.
        /// </summary>
        public static string Error_ComparableFileHash_CompareTo_Fragment_Size_Mismatch {
            get {
                return ResourceManager.GetString("Error_ComparableFileHash_CompareTo_Fragment_Size_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompleteMatch and CompleteMismatch is defined incorrectly, CompleteMatch must be greater than CompleteMismatch.
        /// </summary>
        public static string Error_ComparableFileHash_CompleteMatch_and_CompleteMismatch_is_defined_incorrectly {
            get {
                return ResourceManager.GetString("Error_ComparableFileHash_CompleteMatch_and_CompleteMismatch_is_defined_incorrectl" +
                        "y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragment index &apos;{0:N0}&apos; is out of bounds, there is &apos;{1:N0}&apos; fragments in the file.
        /// </summary>
        public static string Error_ComparableFileHash_Fragment_index_is_out_of_bounds {
            get {
                return ResourceManager.GetString("Error_ComparableFileHash_Fragment_index_is_out_of_bounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid fragment size.
        /// </summary>
        public static string Error_ComparableFileHash_Invalid_fragment_size {
            get {
                return ResourceManager.GetString("Error_ComparableFileHash_Invalid_fragment_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The random access for hashing is not supported.
        /// </summary>
        public static string Error_ComparableFileHash_The_random_access_for_hashing_is_not_supported {
            get {
                return ResourceManager.GetString("Error_ComparableFileHash_The_random_access_for_hashing_is_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash.Compute is called with an invalid parameter &apos;dataForHash&apos; that is null.
        /// </summary>
        public static string Error_Compute_Hash_Compute_is_called_with_an_invalid_parameter {
            get {
                return ResourceManager.GetString("Error_Compute_Hash_Compute_is_called_with_an_invalid_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to close the file search handle. .
        /// </summary>
        public static string Error_Failed_to_close_the_file_search_handle {
            get {
                return ResourceManager.GetString("Error_Failed_to_close_the_file_search_handle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the next file. .
        /// </summary>
        public static string Error_Failed_to_find_the_next_file {
            get {
                return ResourceManager.GetString("Error_Failed_to_find_the_next_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string Error_File_not_found {
            get {
                return ResourceManager.GetString("Error_File_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; does not exist.
        /// </summary>
        public static string Error_File_x_not_found {
            get {
                return ResourceManager.GetString("Error_File_x_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is greater than the allowed maximum.
        /// </summary>
        public static string Error_The_value_is_greater_than_the_allowed_maximum {
            get {
                return ResourceManager.GetString("Error_The_value_is_greater_than_the_allowed_maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is less than the allowed minimum.
        /// </summary>
        public static string Error_The_value_is_less_than_the_allowed_minimum {
            get {
                return ResourceManager.GetString("Error_The_value_is_less_than_the_allowed_minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not a an integer.
        /// </summary>
        public static string Error_The_value_is_not_a_an_integer {
            get {
                return ResourceManager.GetString("Error_The_value_is_not_a_an_integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not a valid number.
        /// </summary>
        public static string Error_The_value_is_not_a_valid_number {
            get {
                return ResourceManager.GetString("Error_The_value_is_not_a_valid_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert the size to bytes, unknown SizeUnits parameter.
        /// </summary>
        public static string Error_Unable_to_convert_the_size_to_bytes_unknown_SizeUnits {
            get {
                return ResourceManager.GetString("Error_Unable_to_convert_the_size_to_bytes_unknown_SizeUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set the file offset.
        /// </summary>
        public static string Error_Unable_to_set_the_file_offset {
            get {
                return ResourceManager.GetString("Error_Unable_to_set_the_file_offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown file extension inclusion type.
        /// </summary>
        public static string Error_Unknown_file_extension_inclusion_type {
            get {
                return ResourceManager.GetString("Error_Unknown_file_extension_inclusion_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculates file hash while read files, compares the hash values. The hash is cached to prevent reading files twice.
        /// </summary>
        public static string FileHashComparer_Description {
            get {
                return ResourceManager.GetString("FileHashComparer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Hash Comparer.
        /// </summary>
        public static string FileHashComparer_Name {
            get {
                return ResourceManager.GetString("FileHashComparer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting: {0}.
        /// </summary>
        public static string Log_Deleting_Name {
            get {
                return ResourceManager.GetString("Log_Deleting_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting: {0}; {1}.
        /// </summary>
        public static string Log_Deleting_Name_Size {
            get {
                return ResourceManager.GetString("Log_Deleting_Name_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled. .
        /// </summary>
        public static string Log_Deletion_Cancelled {
            get {
                return ResourceManager.GetString("Log_Deletion_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done. .
        /// </summary>
        public static string Log_Deletion_Completed {
            get {
                return ResourceManager.GetString("Log_Deletion_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string Log_Error_Deleting_failed_Exception {
            get {
                return ResourceManager.GetString("Log_Error_Deleting_failed_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting failed: {0}.
        /// </summary>
        public static string Log_Error_Deleting_failed_Name {
            get {
                return ResourceManager.GetString("Log_Error_Deleting_failed_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted: {0:N0} files; Freed: {1:N0} bytes..
        /// </summary>
        public static string Log_Files_Deletion_Summary {
            get {
                return ResourceManager.GetString("Log_Files_Deletion_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing deletion of the marked duplicates..
        /// </summary>
        public static string Log_Performing_deletion_of_the_marked_duplicates {
            get {
                return ResourceManager.GetString("Log_Performing_deletion_of_the_marked_duplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmarking: {0}.
        /// </summary>
        public static string Log_Unmarking_FullFileName {
            get {
                return ResourceManager.GetString("Log_Unmarking_FullFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the program.
        /// </summary>
        public static string Ui_About_the_Program_Header {
            get {
                return ResourceManager.GetString("Ui_About_the_Program_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate File Tool is a program for search and removal of a duplicated files. It is FREE and Open Source, made to be extensible with a different search algorithms..
        /// </summary>
        public static string Ui_About_the_Program_Text {
            get {
                return ResourceManager.GetString("Ui_About_the_Program_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the path where the duplicated files should be automatically selected for deletion..
        /// </summary>
        public static string Ui_AutoSelectByPath_Description {
            get {
                return ResourceManager.GetString("Ui_AutoSelectByPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Ui_Cancel_Search_Button_Text {
            get {
                return ResourceManager.GetString("Ui_Cancel_Search_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count the entered size in Bytes.
        /// </summary>
        public static string Ui_Count_size_in_Bytes {
            get {
                return ResourceManager.GetString("Ui_Count_size_in_Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count the entered size in Gigabytes.
        /// </summary>
        public static string Ui_Count_size_in_Gigabytes {
            get {
                return ResourceManager.GetString("Ui_Count_size_in_Gigabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count the entered size in Kilobytes.
        /// </summary>
        public static string Ui_Count_size_in_Kilobytes {
            get {
                return ResourceManager.GetString("Ui_Count_size_in_Kilobytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count the entered size in Megabytes.
        /// </summary>
        public static string Ui_Count_size_in_Megabytes {
            get {
                return ResourceManager.GetString("Ui_Count_size_in_Megabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate files group #.
        /// </summary>
        public static string Ui_Duplicate_files_group_N {
            get {
                return ResourceManager.GetString("Ui_Duplicate_files_group_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Duplicated size: .
        /// </summary>
        public static string Ui_Duplicated_size {
            get {
                return ResourceManager.GetString("Ui_Duplicated_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current sorting order is Ascending.
        /// </summary>
        public static string Ui_Duplicates_Sorting_Order_Ascending {
            get {
                return ResourceManager.GetString("Ui_Duplicates_Sorting_Order_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current sorting order is Descending.
        /// </summary>
        public static string Ui_Duplicates_Sorting_Order_Descending {
            get {
                return ResourceManager.GetString("Ui_Duplicates_Sorting_Order_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string Ui_Errors_Tab_Header {
            get {
                return ResourceManager.GetString("Ui_Errors_Tab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions.
        /// </summary>
        public static string Ui_Extensions_GroupBox_Header {
            get {
                return ResourceManager.GetString("Ui_Extensions_GroupBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Files: .
        /// </summary>
        public static string Ui_Files {
            get {
                return ResourceManager.GetString("Ui_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing: .
        /// </summary>
        public static string Ui_Progress_Analyzing {
            get {
                return ResourceManager.GetString("Ui_Progress_Analyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing: .
        /// </summary>
        public static string Ui_Progress_Comparing {
            get {
                return ResourceManager.GetString("Ui_Progress_Comparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Cancelled..
        /// </summary>
        public static string Ui_Progress_Duplicates_Search_Cancelled {
            get {
                return ResourceManager.GetString("Ui_Progress_Duplicates_Search_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        public static string Ui_Progress_Duplicates_Search_Done {
            get {
                return ResourceManager.GetString("Ui_Progress_Duplicates_Search_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning files: .
        /// </summary>
        public static string Ui_Progress_Scanning {
            get {
                return ResourceManager.GetString("Ui_Progress_Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Select by Path.
        /// </summary>
        public static string Ui_Results_Auto_select_by_path {
            get {
                return ResourceManager.GetString("Ui_Results_Auto_select_by_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all results.
        /// </summary>
        public static string Ui_Results_Clear_Results {
            get {
                return ResourceManager.GetString("Ui_Results_Clear_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected Files.
        /// </summary>
        public static string Ui_Results_Delete_Marked_Files {
            get {
                return ResourceManager.GetString("Ui_Results_Delete_Marked_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Groups:.
        /// </summary>
        public static string Ui_Results_Duplicate_Groups_Count {
            get {
                return ResourceManager.GetString("Ui_Results_Duplicate_Groups_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated Bytes:.
        /// </summary>
        public static string Ui_Results_Duplicated_Size {
            get {
                return ResourceManager.GetString("Ui_Results_Duplicated_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates Information.
        /// </summary>
        public static string Ui_Results_Duplicates_Information_GroupBox_Header {
            get {
                return ResourceManager.GetString("Ui_Results_Duplicates_Information_GroupBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Ui_Results_Page {
            get {
                return ResourceManager.GetString("Ui_Results_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        public static string Ui_Results_Page_Number_Split {
            get {
                return ResourceManager.GetString("Ui_Results_Page_Number_Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selection.
        /// </summary>
        public static string Ui_Results_Reset_selection {
            get {
                return ResourceManager.GetString("Ui_Results_Reset_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be Deleted:.
        /// </summary>
        public static string Ui_Results_Selected_for_deletion_size {
            get {
                return ResourceManager.GetString("Ui_Results_Selected_for_deletion_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Ui_Results_Tab_Header {
            get {
                return ResourceManager.GetString("Ui_Results_Tab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Duplicates.
        /// </summary>
        public static string Ui_Search_Button_Text {
            get {
                return ResourceManager.GetString("Ui_Search_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum:.
        /// </summary>
        public static string Ui_Search_Size_Maximum_Label {
            get {
                return ResourceManager.GetString("Ui_Search_Size_Maximum_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum:.
        /// </summary>
        public static string Ui_Search_Size_Minimum_Label {
            get {
                return ResourceManager.GetString("Ui_Search_Size_Minimum_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Ui_Search_Tab_Header {
            get {
                return ResourceManager.GetString("Ui_Search_Tab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Ui_Settings_Tab_Header {
            get {
                return ResourceManager.GetString("Ui_Settings_Tab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Ui_Size_GroupBox_Header {
            get {
                return ResourceManager.GetString("Ui_Size_GroupBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selected to the list.
        /// </summary>
        public static string Ui_ToolTip_Add_selected_to_the_list {
            get {
                return ResourceManager.GetString("Ui_ToolTip_Add_selected_to_the_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate file search errors.
        /// </summary>
        public static string Ui_ToolTip_Errors_Tab {
            get {
                return ResourceManager.GetString("Ui_ToolTip_Errors_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The files with the listed extensions will be excluded from the search.
        /// </summary>
        public static string Ui_ToolTip_Files_with_the_listed_extensions_will_be_excluded {
            get {
                return ResourceManager.GetString("Ui_ToolTip_Files_with_the_listed_extensions_will_be_excluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the files with the listed extensions will be included in the search.
        /// </summary>
        public static string Ui_ToolTip_Only_the_files_with_the_listed_extensions_included {
            get {
                return ResourceManager.GetString("Ui_ToolTip_Only_the_files_with_the_listed_extensions_included", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the file in explorer.
        /// </summary>
        public static string Ui_ToolTip_Open_File_In_Explorer {
            get {
                return ResourceManager.GetString("Ui_ToolTip_Open_File_In_Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate file search results.
        /// </summary>
        public static string Ui_ToolTip_Results_Tab {
            get {
                return ResourceManager.GetString("Ui_ToolTip_Results_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate files search.
        /// </summary>
        public static string Ui_ToolTip_Search_Tab {
            get {
                return ResourceManager.GetString("Ui_ToolTip_Search_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate file tool settings.
        /// </summary>
        public static string Ui_ToolTip_Settings_Tab {
            get {
                return ResourceManager.GetString("Ui_ToolTip_Settings_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select for deletion.
        /// </summary>
        public static string Ui_ToolTip_Toggle_Mark_For_Deletion {
            get {
                return ResourceManager.GetString("Ui_ToolTip_Toggle_Mark_For_Deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmark.
        /// </summary>
        public static string Ui_ToolTip_Toggle_Unmark_For_Deletion {
            get {
                return ResourceManager.GetString("Ui_ToolTip_Toggle_Unmark_For_Deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid selection, encountered a group with all files selected, at leas one file should be left unselected. The group will be ignored..
        /// </summary>
        public static string Warning_Encountered_a_group_with_all_files_selected {
            get {
                return ResourceManager.GetString("Warning_Encountered_a_group_with_all_files_selected", resourceCulture);
            }
        }
    }
}
